# Based on https://github.com/firezone/firezone/blob/4ac447ad1f0c65db3660f4311ad7c1d9040fa0e1/docker-compose.yml

services:
  postgres:
    image: postgres:15.5
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-5432}
      POSTGRES_DB: ${POSTGRES_DB:?err}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    ports:
      - 127.0.0.1:5432:5432/tcp
    networks:
      - postgres

networks:
  postgres:
    name: postgres
    driver: bridge

volumes:
  postgres-data:
